// metadata sẽ không hoạt động trong 'use client'
//đây là cách giải quyết.

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "View Detail Blog",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <>
            {children}
        </>
    );
}